name: Update README
on:
  push:
    paths:
      - '**.md'
      - '!README.md'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate Dynamic Documentation
        run: |
          # Génère le contenu entre les marqueurs
          START_MARKER="<!-- START_CONTENT -->"
          END_MARKER="<!-- END_CONTENT -->"
          
          # Crée le contenu dynamique
          DOCS_CONTENT=$(find . -name "*.md" ! -name "README.md" -print0 | xargs -0 -I {} sh -c 'echo "\n## {}\n"; cat {}; echo "\n---"')
          
          # Met à jour le README avec awk
          awk -v start="$START_MARKER" -v end="$END_MARKER" -v content="$DOCS_CONTENT" '
            BEGIN { in_block=0 }
            $0 ~ start { print; print content; in_block=1; next }
            $0 ~ end { in_block=0 }
            !in_block { print }
          ' README.md > TEMP.md
          
          mv TEMP.md README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Vérifie les modifications
          git diff --exit-code || {
            git add README.md
            git commit -m "📚 Documentation dynamique mise à jour"
            git pull --rebase  # Gère les conflits potentiels
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          }
