name: Update README Dynamically

on:
  push:
    paths:
      - '**.md'
      - '!README.md'
  workflow_dispatch:  # Permet le déclenchement manuel par bouton

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate dynamic documentation section
        run: |
          START_MARKER="<!-- START_CONTENT -->"
          END_MARKER="<!-- END_CONTENT -->"
          TMP_FILE=$(mktemp)

          # Liste triée des fichiers .md à documenter (hors README)
          FILES=$(find . -maxdepth 1 -name "*.md" ! -name "README.md" | sort)

          # Génère la table des fichiers avec liens
          echo "# 📚 Documentation Index" > docs_content.md
          echo "" >> docs_content.md
          for f in $FILES; do
            fname=$(basename "$f")
            echo "- [${fname}]($fname)" >> docs_content.md
          done
          echo "" >> docs_content.md

          # Ajoute le contenu de chaque fichier, séparé par une ligne horizontale
          for f in $FILES; do
            echo "" >> docs_content.md
            cat "$f" >> docs_content.md
            echo -e "\n\n---\n" >> docs_content.md
          done

          DOCS_CONTENT=$(cat docs_content.md)

          # Met à jour le README entre les marqueurs
          awk -v start="$START_MARKER" -v end="$END_MARKER" -v content="$DOCS_CONTENT" '
            BEGIN {in_block=0}
            $0 ~ start {print; print content; in_block=1; next}
            $0 ~ end {in_block=0}
            !in_block {print}
          ' README.md > "$TMP_FILE"

          mv "$TMP_FILE" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git fetch origin main
          git reset --hard origin/main

          if ! git diff --quiet; then
            git add README.md
            git commit -m "📚 Mise à jour automatique de la documentation"
            git pull --rebase origin main
            git push origin main
          else
            echo "Aucun changement détecté."
          fi
