name: Update README Dynamically
on:
  push:
    paths:
      - '**.md'
      - '!README.md'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate dynamic documentation section
        run: |
          START_MARKER="<!-- START_CONTENT -->"
          END_MARKER="<!-- END_CONTENT -->"
          TMP="README.tmp.md"

          # Génère le contenu à insérer
          DOCS_CONTENT=$(find . -name "*.md" ! -name "README.md" | sort | xargs -I {} sh -c 'echo -e "\n## {}"; cat {}; echo -e "\n---"')

          # Construit le nouveau README
          awk -v start="$START_MARKER" -v end="$END_MARKER" -v content="$DOCS_CONTENT" '
            BEGIN {in_block=0}
            $0 ~ start {print; print content; in_block=1; next}
            $0 ~ end {in_block=0}
            !in_block {print}
          ' README.md > "$TMP"

          mv "$TMP" README.md

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Synchronise avec la branche distante pour éviter les conflits
          git fetch origin
          git rebase origin/main

          # Commit si modification
          if ! git diff --quiet; then
            git add README.md
            git commit -m "📚 Mise à jour dynamique de la documentation"
            git pull --rebase origin main
            git push origin HEAD:main
          else
            echo "Aucun changement à pousser."
          fi
