name: Insert file tree into README

on:
  workflow_dispatch:  # Déclenchement manuel par bouton

permissions:
  contents: write

jobs:
  update-readme-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate file tree
        run: |
          # Installe tree si besoin
          sudo apt-get update && sudo apt-get install -y tree

          # Génère l'arborescence, ignore .git et README.md
          tree -I '.git|node_modules' -a -F > tree.txt

          # Prépare le bloc à insérer dans le README
          echo '```
          cat tree.txt >> tree_block.txt
          echo '```' >> tree_block.txt

      - name: Insert file tree into README
        run: |
          START_MARKER="<!-- FILE_TREE_START -->"
          END_MARKER="<!-- FILE_TREE_END -->"
          TMP_FILE=$(mktemp)

          TREE_CONTENT=$(cat tree_block.txt)

          # Remplace le bloc entre les marqueurs dans README.md
          awk -v start="$START_MARKER" -v end="$END_MARKER" -v content="$TREE_CONTENT" '
            BEGIN {in_block=0}
            $0 ~ start {print; print content; in_block=1; next}
            $0 ~ end {in_block=0}
            !in_block {print}
          ' README.md > "$TMP_FILE"

          mv "$TMP_FILE" README.md

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add README.md
            git commit -m "🔄 Update file tree in README"
            git push
          else
            echo "No changes to commit."
          fi
